backend:
  name: github
  repo: ryansaballa/texostudio.git   # change this
  branch: main                       # or your default branch

media_folder: "images"               # where files get saved in your repo
public_folder: "/uploads"            # how those files are referenced on the site

publish_mode: editorial_workflow     # optional: review via PRs

collections:
  - name: "articles"
    label: "Articles"
    folder: "article/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
