backend:
  name: github
  repo: ryansaballa/texostudio   # change this
  branch: master                       # or your default branch

media_folder: "images"               # where files get saved in your repo
public_folder: "/uploads"            # how those files are referenced on the site

publish_mode: editorial_workflow     # optional: review via PRs

collections:
  - name: "posts"
    label: "Posts"
    folder: "article/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
      - { name: "layout", label: "Layout", widget: "hidden", default: "layouts/post.njk" }

